services:
  max-forward-bot:
    build:
      context: .
      args:
        PIP_INDEX_URL: https://mirrors.aliyun.com/pypi/simple/
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Это сохраняет config.json даже после удаления контейнера
